parameters:
  aw_email_templating.templating.engine.class: Accurateweb\EmailTemplateBundle\Template\Engine\SimpleTemplateEngine

  aw_email_template_admin.email_template_group: Message templates
  aw_email_template_admin.email_template_label: Email Templates
  aw_email_template_admin.class: ~

services:
  aw_email_template_admin.model_manager:
     class: Accurateweb\EmailTemplateBundle\Model\ModelManager
     arguments:
       - "@doctrine"
       - "@aw_email_templating.template.factory"

  aw_email_template_admin.email_template:
    class: Accurateweb\EmailTemplateBundle\Admin\EmailTemplateAdmin
    tags:
        -
          name: sonata.admin
          manager_type: orm
          group: %aw_email_template_admin.email_template_group%
          label: %aw_email_template_admin.email_template_label%
          label_catalogue: PropelEmailTemplateAdminBundle
    arguments:
        - null
        - %aw_email_template_admin.class%
        - SonataAdminBundle:CRUD
    calls:
        - [setModelManager, ['@aw_email_template_admin.model_manager'] ]
        - [setTemplate, [edit, AccuratewebEmailTemplateBundle:EmailTemplateAdmin:edit.html.twig]]

  aw_email_templating.template.loader.default:
    class: Accurateweb\EmailTemplateBundle\Template\Loader\DefaultTemplateLoader

  aw_email_templating.template.loader.doctrine:
    class: Accurateweb\EmailTemplateBundle\Template\Loader\DoctrineTemplateLoader
    arguments:
      - "@doctrine.orm.entity_manager"
      - ~

  aw_email_templating.template.engine:
    class: %aw_email_templating.templating.engine.class%

  aw_email_templating.template.factory:
    class: Accurateweb\EmailTemplateBundle\Email\Factory\EmailFactory
    arguments:
      - ~
      - "@aw_email_templating.template.engine"
      - '@event_dispatcher'

  aw_email_templating.type.supported_variables:
    class: Accurateweb\EmailTemplateBundle\Form\Type\SupportedVariablesType
    tags:
      - { name: "form.type" }

  aw_email_templating.listener.image_as_attachment:
    class: Accurateweb\EmailTemplateBundle\EventListener\ImagesAsAttachment
    arguments: ['%kernel.root_dir%/../web', '@logger', ~]
    public: false
    autowire: false
    tags:
      - { name: kernel.event_listener, event: aw.email.message.create, method: onCreateMessage }